spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://db:3306/simcard
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

