spring:
  spring:
    application:
      name: voucher-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  datasource:
    url: jdbc:mysql://db:3306/simcard
    username: root
    password: p@ssword
    driver-class-name: com.mysql.cj.jdbc.Driver

  zipkin:
    base-url: http://zipkin:9411
    enabled: false
    sleuth:
      log.slf4j.whitelisted-mdc-keys: x-cid
      propagation-keys: x-cid

health:
  config:
    enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://discovery:8761/eureka}
  instance:
    #    hostname: ${HOST_NAME:${spring.application.name}}
    preferIpAddress: true

application-short-name: vc
application-context-name: voucher-service
springdoc.api-docs.path: /${application-context-name}/v2/api-docs

springdoc:
  api-docs:
    enabled: true

application:
  allowedOrigins: http://localhost:8080

endpoint:
  internalApiUrl: http://third-party-service:8099
  getVoucherUri: /api/v1/voucher


