spring:
  application:
    name: third-party-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  datasource:
    url: jdbc:mysql://db:3306/voucher
    username: root
    password: p@ssword
    driver-class-name: com.mysql.cj.jdbc.Driver

application-short-name: tps
application-context-name: third-party-service
springdoc.api-docs.path: /${application-context-name}/v2/api-docs

springdoc:
  api-docs:
    enabled: true

application:
  allowedOrigins: http://db:8081
