spring:
  application:
    name: third-party-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/voucher_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

application-short-name: tps
application-context-name: third-party-service
springdoc.api-docs.path: /${application-context-name}/v2/api-docs

springdoc:
  api-docs:
    enabled: true

logbook:
  format:
    style: json
  filter:
  body: secondField
  exclude: [/swagger-ui.html]

application:
  allowedOrigins: http://localhost:8081
